from __future__ import annotations

FEATURE_NAMES: tuple[str, ...] = (
    "five_min_return",
    "one_hour_return",
    "volume_acceleration",
    "liquidity_depth",
    "liquidity_change",
    "buy_sell_ratio",
    "unique_buyers_estimate",
    "pair_age_minutes",
    "holder_count",
    "holder_growth",
    "top_holder_concentration",
    "spread_estimate",
    "volatility",
    "venue_agreement",
    "mention_velocity",
    "website_presence",
    "github_presence_public",
    "suspicious_contract_flags",
    "deployer_history_available",
    "narrative_acceleration",
    "ignition_signal",
    "liquidity_withdrawal_signal",
    "lp_removal_signal",
    "recidivism_score",
    "prelaunch_priority",
    "catalyst_proximity_hours",
    "narrative_cluster_growth_7d",
    "shill_channel_diversity",
    "prelaunch_narrative_velocity",
    "kol_velocity",
    "github_star_velocity",
    "hf_download_velocity",
    "rpc_pool_health",
    "collapse_probability_24h",
    "lifecycle_phase",
)

FEATURE_LABELS: dict[str, str] = {
    "five_min_return": "5m return",
    "one_hour_return": "1h return",
    "volume_acceleration": "Volume acceleration",
    "liquidity_depth": "Liquidity depth",
    "liquidity_change": "Liquidity change",
    "buy_sell_ratio": "Buy/sell ratio",
    "unique_buyers_estimate": "Unique buyers estimate",
    "pair_age_minutes": "Pair age",
    "holder_count": "Holder count",
    "holder_growth": "Holder growth",
    "top_holder_concentration": "Top holder concentration",
    "spread_estimate": "Spread estimate",
    "volatility": "Volatility",
    "venue_agreement": "Venue agreement",
    "mention_velocity": "Mention velocity",
    "website_presence": "Website presence",
    "github_presence_public": "Public GitHub presence",
    "suspicious_contract_flags": "Suspicious contract flags",
    "deployer_history_available": "Deployer history available",
    "narrative_acceleration": "Narrative acceleration",
    "ignition_signal": "Ignition signal",
    "liquidity_withdrawal_signal": "Liquidity withdrawal signal",
    "lp_removal_signal": "On-chain LP burn/withdrawal signal",
    "recidivism_score": "Syndicate recidivism score",
    "prelaunch_priority": "Prelaunch priority",
    "catalyst_proximity_hours": "Hours to nearest scheduled catalyst",
    "narrative_cluster_growth_7d": "Narrative cluster growth (7d)",
    "shill_channel_diversity": "Distinct shill channels (24h)",
    "prelaunch_narrative_velocity": "Pre-pool narrative velocity",
    "kol_velocity": "Distinct KOL channels mentioning (24h)",
    "github_star_velocity": "GitHub star velocity (stars/day)",
    "hf_download_velocity": "HuggingFace download velocity (downloads/day)",
    "rpc_pool_health": "Chain RPC pool health",
    "collapse_probability_24h": "Modeled 24h collapse probability",
    "lifecycle_phase": "Hype-lifecycle phase (0=seeding..4=collapse)",
}
